
services:
  
  db:
    image: postgres:17
    restart: unless-stopped
    container_name: db_nv36
    ports:
     - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: Novousmansky_vestnik
    volumes:
      - db_data:/var/lib/postgresql/data


  backend:
    container_name: backend_nv36
    restart: unless-stopped
    build:
      context: ./Backend_website/config
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file: 
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: Novousmansky_vestnik
    volumes:
      - ./Backend_website/media:/app/media_local:rw
      - static_volume:/app/staticfiles
    depends_on:
      - db


  frontend:
    container_name: frontend_nv36
    restart: unless-stopped
    build:
      context: ./Frontend_website/frontendfile
      dockerfile: Dockerfile
      
    
    expose:
      - "80"
    depends_on:
      - backend



  nginx:

    image: nginx:alpine
    container_name: nginx_nv36
    restart: unless-stopped
    ports:
      - "84:80"
    volumes:

      - static_volume:/app/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
  static_volume:

